//Sentiment Action Types
export const SET_SENTIMENT_FILE = 'SET_SENTIMENT_FILE';
export const SENTIMENT_LOADING = 'SENTIMENT_LOADING';
export const SET_RESULT_SENTIMENT = 'SET_RESULT_SENTIMENT';
export const RESET_SENTIMENT = 'RESET_SENTIMENT';
export const SET_SENTIMENT_HISTORY = 'SET_SENTIMENT_HISTORY';


// Speech to Text Action Types 
export const SET_SPEECH_FILE = 'SET_SPEECH_FILE';
export const SPEECH_LOADING = 'SPEECH_LOADING';
export const SET_RESULT_SPEECH = 'SET_RESULT_SPEECH';
export const RESET_SPEECH_TEXT = 'RESET_SPEECH_TEXT';


// Problem Identification Action Types
export const SET_FILE_TYPE  = 'SET_FILE_TYPE';
export const RESET_PROBLEM_FILE = 'RESET_PROBLEM_FILE';
export const SET_PROBLEM_FILE = 'SET_PROBLEM_FILE';
export const PROBLEM_LOADING = 'PROBLEM_LOADING';
export const PROBLEM_RESULT  = 'PROBLEM_RESULT';
export const SET_PROBLEMS_HISTORY = 'SET_PROBLEMS_HISTORY';


//Data Analytics
export const SET_FREQ_COUNT  = 'SET_FREQ_COUNT';
export const RESOURCE_LOADING = 'RESOURCE_LOADING';

//AUDIO FILE STATUS
export const SET_FILE_STATUS = 'SET_FILE_STATUS';
export const RESET_FILE_STATUS = 'RESET_FILE_STATUS';




